export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

type Table<Row, Insert, Update> = { Row: Row; Insert: Insert; Update: Update; Relationships: [] };

export type Database = {
  public: {
    Tables: {
      school_years: Table<{ id:string; label:string; starts_on:string; ends_on:string; archived:boolean; created_at:string }, { id?:string; label:string; starts_on:string; ends_on:string; archived?:boolean; created_at?:string }, { id?:string; label?:string; starts_on?:string; ends_on?:string; archived?:boolean; created_at?:string }>;
      courses: Table<{ id:string; code:string|null; name:string; created_at:string }, { id?:string; code?:string|null; name:string; created_at?:string }, { id?:string; code?:string|null; name?:string; created_at?:string }>;
      profiles: Table<{ id:string; email:string; display_name:string; role:string; created_at:string }, { id:string; email:string; display_name:string; role:string; created_at?:string }, { id?:string; email?:string; display_name?:string; role?:string; created_at?:string }>;
      students: Table<{ id:string; school_email:string|null; display_name:string; first_name:string|null; last_name:string|null; external_student_key:string|null; created_at:string; updated_at:string }, { id?:string; school_email?:string|null; display_name:string; first_name?:string|null; last_name?:string|null; external_student_key?:string|null; created_at?:string; updated_at?:string }, { id?:string; school_email?:string|null; display_name?:string; first_name?:string|null; last_name?:string|null; external_student_key?:string|null; created_at?:string; updated_at?:string }>;
      student_accounts: Table<{ student_id:string; profile_id:string; linked_at:string }, { student_id:string; profile_id:string; linked_at?:string }, { student_id?:string; profile_id?:string; linked_at?:string }>;
      sections: Table<{ id:string; course_id:string; school_year_id:string; name:string; active:boolean; created_at:string }, { id?:string; course_id:string; school_year_id:string; name:string; active?:boolean; created_at?:string }, { id?:string; course_id?:string; school_year_id?:string; name?:string; active?:boolean; created_at?:string }>;
      teacher_sections: Table<{ teacher_id:string; section_id:string }, { teacher_id:string; section_id:string }, { teacher_id?:string; section_id?:string }>;
      enrollments: Table<{ id:string; student_id:string; section_id:string; enrolled_on:string; exited_on:string|null; active:boolean; created_at:string }, { id?:string; student_id:string; section_id:string; enrolled_on:string; exited_on?:string|null; active?:boolean; created_at?:string }, { id?:string; student_id?:string; section_id?:string; enrolled_on?:string; exited_on?:string|null; active?:boolean; created_at?:string }>;
      grading_periods: Table<{ id:string; section_id:string; code:string; name:string; starts_on:string|null; ends_on:string|null }, { id?:string; section_id:string; code:string; name:string; starts_on?:string|null; ends_on?:string|null }, { id?:string; section_id?:string; code?:string; name?:string; starts_on?:string|null; ends_on?:string|null }>;
      grading_categories: Table<{ id:string; section_id:string; name:string; weight:number; drop_lowest:number; late_deduction:number }, { id?:string; section_id:string; name:string; weight:number; drop_lowest?:number; late_deduction?:number }, { id?:string; section_id?:string; name?:string; weight?:number; drop_lowest?:number; late_deduction?:number }>;
      assignments: Table<{ id:string; section_id:string; category_id:string; grading_period_id:string|null; title:string; assignment_type:string; assignment_date:string; points_possible:number; allow_retakes:boolean; late_deduction_override:number|null; created_by:string|null; created_at:string; updated_at:string }, { id?:string; section_id:string; category_id:string; grading_period_id?:string|null; title:string; assignment_type:string; assignment_date:string; points_possible:number; allow_retakes?:boolean; late_deduction_override?:number|null; created_by?:string|null; created_at?:string; updated_at?:string }, { id?:string; section_id?:string; category_id?:string; grading_period_id?:string|null; title?:string; assignment_type?:string; assignment_date?:string; points_possible?:number; allow_retakes?:boolean; late_deduction_override?:number|null; created_by?:string|null; created_at?:string; updated_at?:string }>;
      grade_records: Table<{ id:string; assignment_id:string; student_id:string; missing:boolean; exempt:boolean; created_at:string; updated_at:string }, { id?:string; assignment_id:string; student_id:string; missing?:boolean; exempt?:boolean; created_at?:string; updated_at?:string }, { id?:string; assignment_id?:string; student_id?:string; missing?:boolean; exempt?:boolean; created_at?:string; updated_at?:string }>;
      grade_attempts: Table<{ id:string; grade_record_id:string; attempt_number:number; points_earned:number; occurred_on:string; is_late:boolean; entered_by:string|null; created_at:string }, { id?:string; grade_record_id:string; attempt_number:number; points_earned:number; occurred_on:string; is_late?:boolean; entered_by?:string|null; created_at?:string }, { id?:string; grade_record_id?:string; attempt_number?:number; points_earned?:number; occurred_on?:string; is_late?:boolean; entered_by?:string|null; created_at?:string }>;
      grade_changes: Table<{ id:string; grade_record_id:string; changed_by:string|null; changed_at:string; old_value:Json|null; new_value:Json; action:string }, { id?:string; grade_record_id:string; changed_by?:string|null; changed_at?:string; old_value?:Json|null; new_value:Json; action:string }, { id?:string; grade_record_id?:string; changed_by?:string|null; changed_at?:string; old_value?:Json|null; new_value?:Json; action?:string }>;
      grade_issue_reports: Table<{ id:string; grade_record_id:string; student_id:string; message:string; status:string; created_at:string; resolved_at:string|null; resolved_by:string|null }, { id?:string; grade_record_id:string; student_id:string; message:string; status?:string; created_at?:string; resolved_at?:string|null; resolved_by?:string|null }, { id?:string; grade_record_id?:string; student_id?:string; message?:string; status?:string; created_at?:string; resolved_at?:string|null; resolved_by?:string|null }>;
      power_school_snapshots: Table<{ id:string; student_id:string; section_id:string; grading_period_id:string|null; captured_at:string; powerschool_percent:number; website_percent:number; note:string|null }, { id?:string; student_id:string; section_id:string; grading_period_id?:string|null; captured_at?:string; powerschool_percent:number; website_percent:number; note?:string|null }, { id?:string; student_id?:string; section_id?:string; grading_period_id?:string|null; captured_at?:string; powerschool_percent?:number; website_percent?:number; note?:string|null }>;
      roster_import_batches: Table<{ id:string; teacher_id:string; source_filename:string; parsed_rows:Json; warnings:Json; status:string; result_summary:Json|null; created_at:string; expires_at:string; imported_at:string|null }, { id?:string; teacher_id:string; source_filename:string; parsed_rows:Json; warnings?:Json; status?:string; result_summary?:Json|null; created_at?:string; expires_at?:string; imported_at?:string|null }, { id?:string; teacher_id?:string; source_filename?:string; parsed_rows?:Json; warnings?:Json; status?:string; result_summary?:Json|null; created_at?:string; expires_at?:string; imported_at?:string|null }>;
    };
    Views: { [_ in never]: never };
    Functions: { [_ in never]: never };
    Enums: { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
  };
};
