export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

type Table<Row, Insert, Update> = { Row: Row; Insert: Insert; Update: Update; Relationships: [] };

export type Database = {
  public: {
    Tables: {
      school_years: Table<{ id:string; label:string; starts_on:string; ends_on:string; archived:boolean; created_at:string }, { id?:string; label:string; starts_on:string; ends_on:string; archived?:boolean; created_at?:string }, { id?:string; label?:string; starts_on?:string; ends_on?:string; archived?:boolean; created_at?:string }>;
      courses: Table<{ id:string; code:string|null; name:string; created_at:string }, { id?:string; code?:string|null; name:string; created_at?:string }, { id?:string; code?:string|null; name?:string; created_at?:string }>;
      course_offerings: Table<{ id:string; course_id:string; school_year_id:string; active:boolean; created_at:string }, { id?:string; course_id:string; school_year_id:string; active?:boolean; created_at?:string }, { id?:string; course_id?:string; school_year_id?:string; active?:boolean; created_at?:string }>;
      profiles: Table<{ id:string; email:string; display_name:string; role:string; created_at:string }, { id:string; email:string; display_name:string; role:string; created_at?:string }, { id?:string; email?:string; display_name?:string; role?:string; created_at?:string }>;
      students: Table<{ id:string; school_email:string|null; display_name:string; first_name:string|null; last_name:string|null; external_student_key:string|null; created_at:string; updated_at:string }, { id?:string; school_email?:string|null; display_name:string; first_name?:string|null; last_name?:string|null; external_student_key?:string|null; created_at?:string; updated_at?:string }, { id?:string; school_email?:string|null; display_name?:string; first_name?:string|null; last_name?:string|null; external_student_key?:string|null; created_at?:string; updated_at?:string }>;
      student_accounts: Table<{ student_id:string; profile_id:string; linked_at:string }, { student_id:string; profile_id:string; linked_at?:string }, { student_id?:string; profile_id?:string; linked_at?:string }>;
      sections: Table<{ id:string; course_id:string; school_year_id:string; offering_id:string; name:string; active:boolean; period_number:number|null; sort_order:number; created_at:string }, { id?:string; course_id:string; school_year_id:string; offering_id:string; name:string; active?:boolean; period_number?:number|null; sort_order?:number; created_at?:string }, { id?:string; course_id?:string; school_year_id?:string; offering_id?:string; name?:string; active?:boolean; period_number?:number|null; sort_order?:number; created_at?:string }>;
      teacher_sections: Table<{ teacher_id:string; section_id:string }, { teacher_id:string; section_id:string }, { teacher_id?:string; section_id?:string }>;
      enrollments: Table<{ id:string; student_id:string; section_id:string; enrolled_on:string; exited_on:string|null; active:boolean; created_at:string }, { id?:string; student_id:string; section_id:string; enrolled_on:string; exited_on?:string|null; active?:boolean; created_at?:string }, { id?:string; student_id?:string; section_id?:string; enrolled_on?:string; exited_on?:string|null; active?:boolean; created_at?:string }>;
      grading_periods: Table<{ id:string; section_id:string; offering_id:string; code:string; name:string; starts_on:string|null; ends_on:string|null; calculation_mode:string; period_role:string; sort_order:number }, { id?:string; section_id:string; offering_id?:string; code:string; name:string; starts_on?:string|null; ends_on?:string|null; calculation_mode?:string; period_role?:string; sort_order?:number }, { id?:string; section_id?:string; offering_id?:string; code?:string; name?:string; starts_on?:string|null; ends_on?:string|null; calculation_mode?:string; period_role?:string; sort_order?:number }>;
      grading_period_components: Table<{ id:string; parent_period_id:string; component_period_id:string; weight:number; sort_order:number; created_at:string }, { id?:string; parent_period_id:string; component_period_id:string; weight:number; sort_order?:number; created_at?:string }, { id?:string; parent_period_id?:string; component_period_id?:string; weight?:number; sort_order?:number; created_at?:string }>;
      grading_categories: Table<{ id:string; section_id:string; offering_id:string; name:string; code:string; weight:number; drop_lowest:number; late_deduction:number; calculation_method:string; sort_order:number }, { id?:string; section_id:string; offering_id?:string; name:string; code?:string; weight:number; drop_lowest?:number; late_deduction?:number; calculation_method?:string; sort_order?:number }, { id?:string; section_id?:string; offering_id?:string; name?:string; code?:string; weight?:number; drop_lowest?:number; late_deduction?:number; calculation_method?:string; sort_order?:number }>;
      assignment_types: Table<{ id:string; section_id:string; offering_id:string; code:string; name:string; description:string|null; default_category_id:string; default_points_possible:number; default_allow_retakes:boolean; active:boolean; sort_order:number; created_at:string; updated_at:string }, { id?:string; section_id:string; offering_id?:string; code:string; name:string; description?:string|null; default_category_id:string; default_points_possible?:number; default_allow_retakes?:boolean; active?:boolean; sort_order?:number; created_at?:string; updated_at?:string }, { id?:string; section_id?:string; offering_id?:string; code?:string; name?:string; description?:string|null; default_category_id?:string; default_points_possible?:number; default_allow_retakes?:boolean; active?:boolean; sort_order?:number; created_at?:string; updated_at?:string }>;
      assignment_link_groups: Table<{ id:string; offering_id:string; created_by:string; created_at:string }, { id?:string; offering_id:string; created_by:string; created_at?:string }, { id?:string; offering_id?:string; created_by?:string; created_at?:string }>;
      assignments: Table<{ id:string; section_id:string; category_id:string; assignment_type_id:string; grading_period_id:string|null; link_group_id:string|null; title:string; assignment_type:string; assignment_date:string; points_possible:number; allow_retakes:boolean; late_deduction_override:number|null; archived:boolean; archived_at:string|null; created_by:string|null; created_at:string; updated_at:string }, { id?:string; section_id:string; category_id:string; assignment_type_id:string; grading_period_id?:string|null; link_group_id?:string|null; title:string; assignment_type:string; assignment_date:string; points_possible:number; allow_retakes?:boolean; late_deduction_override?:number|null; archived?:boolean; archived_at?:string|null; created_by?:string|null; created_at?:string; updated_at?:string }, { id?:string; section_id?:string; category_id?:string; assignment_type_id?:string; grading_period_id?:string|null; link_group_id?:string|null; title?:string; assignment_type?:string; assignment_date?:string; points_possible?:number; allow_retakes?:boolean; late_deduction_override?:number|null; archived?:boolean; archived_at?:string|null; created_by?:string|null; created_at?:string; updated_at?:string }>;
      grade_records: Table<{ id:string; assignment_id:string; student_id:string; missing:boolean; exempt:boolean; created_at:string; updated_at:string }, { id?:string; assignment_id:string; student_id:string; missing?:boolean; exempt?:boolean; created_at?:string; updated_at?:string }, { id?:string; assignment_id?:string; student_id?:string; missing?:boolean; exempt?:boolean; created_at?:string; updated_at?:string }>;
      grade_attempts: Table<{ id:string; grade_record_id:string; attempt_number:number; points_earned:number; occurred_on:string; is_late:boolean; entered_by:string|null; created_at:string }, { id?:string; grade_record_id:string; attempt_number:number; points_earned:number; occurred_on:string; is_late?:boolean; entered_by?:string|null; created_at?:string }, { id?:string; grade_record_id?:string; attempt_number?:number; points_earned?:number; occurred_on?:string; is_late?:boolean; entered_by?:string|null; created_at?:string }>;
      grade_changes: Table<{ id:string; grade_record_id:string; changed_by:string|null; changed_at:string; old_value:Json|null; new_value:Json; action:string }, { id?:string; grade_record_id:string; changed_by?:string|null; changed_at?:string; old_value?:Json|null; new_value:Json; action:string }, { id?:string; grade_record_id?:string; changed_by?:string|null; changed_at?:string; old_value?:Json|null; new_value?:Json; action?:string }>;
      grade_issue_reports: Table<{ id:string; grade_record_id:string; student_id:string; message:string; status:string; created_at:string; resolved_at:string|null; resolved_by:string|null }, { id?:string; grade_record_id:string; student_id:string; message:string; status?:string; created_at?:string; resolved_at?:string|null; resolved_by?:string|null }, { id?:string; grade_record_id?:string; student_id?:string; message?:string; status?:string; created_at?:string; resolved_at?:string|null; resolved_by?:string|null }>;
      power_school_snapshots: Table<{ id:string; student_id:string; section_id:string; grading_period_id:string|null; captured_at:string; powerschool_percent:number; website_percent:number; note:string|null }, { id?:string; student_id:string; section_id:string; grading_period_id?:string|null; captured_at?:string; powerschool_percent:number; website_percent:number; note?:string|null }, { id?:string; student_id?:string; section_id?:string; grading_period_id?:string|null; captured_at?:string; powerschool_percent?:number; website_percent?:number; note?:string|null }>;
      roster_import_batches: Table<{ id:string; teacher_id:string; source_filename:string; parsed_rows:Json; warnings:Json; status:string; result_summary:Json|null; created_at:string; expires_at:string; imported_at:string|null }, { id?:string; teacher_id:string; source_filename:string; parsed_rows:Json; warnings?:Json; status?:string; result_summary?:Json|null; created_at?:string; expires_at?:string; imported_at?:string|null }, { id?:string; teacher_id?:string; source_filename?:string; parsed_rows?:Json; warnings?:Json; status?:string; result_summary?:Json|null; created_at?:string; expires_at?:string; imported_at?:string|null }>;
    };
    Views: { [_ in never]: never };
    Functions: {
      clear_assignment_scores: { Args: { p_assignment_id:string }; Returns:number };
      create_linked_assignments: { Args: { p_anchor_section_id:string; p_section_ids:string[]; p_assignment_type_id:string; p_category_id:string; p_grading_period_id:string; p_title:string; p_assignment_date:string; p_points_possible:number; p_allow_retakes:boolean }; Returns:{ section_id:string; assignment_id:string; link_group_id:string }[] };
      create_teacher_section: { Args: { p_offering_id:string; p_name:string; p_period_number?:number|null }; Returns:string };
      delete_empty_assignment: { Args: { p_assignment_id:string }; Returns:boolean };
      save_grading_period_settings: { Args: { p_section_id:string; p_periods:Json; p_components:Json }; Returns:void };
    };
    Enums: { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
  };
};