import Link from "next/link";
import { redirect } from "next/navigation";
import { getSectionRoster } from "@/lib/data/roster";
import { getSectionGradingPeriods, getStudentGradeCalculation, getStudentSemesterCalculation } from "@/lib/data/grade-calculation";
import { getTeacherSections } from "@/lib/data/teacher-context";
import { createClient } from "@/lib/supabase/server";
import type { CategoryCalculationMethod, GradingRules } from "@/lib/grading/types";

function formatPercent(value:number|null){return value===null?"—":`${value.toFixed(2)}%`;}
function categoryLabel(category:string,rules:GradingRules){return rules.categoryLabels?.[category]??category;}
function methodLabel(method:CategoryCalculationMethod){return method==="total_points"?"Total points":"Equal assignment %";}
function isSemesterCode(code:string):code is "S1"|"S2"{return code==="S1"||code==="S2";}
type GradeAuditPageProps={searchParams:Promise<{studentId?:string;period?:string;fromSemester?:string}>};

export default async function GradeAuditPage({searchParams}:GradeAuditPageProps){
 const supabase=await createClient(); const {data:claimsData,error:claimsError}=await supabase.auth.getClaims(); const userId=claimsData?.claims?.sub;
 if(claimsError||typeof userId!=="string")redirect("/login");
 const sections=await getTeacherSections(); const section=sections[0]; if(!section)return <main className="content-wrap"><article className="panel"><h1>No teacher section is available.</h1></article></main>;
 const [roster,periods,params]=await Promise.all([getSectionRoster(section.sectionId,"all"),getSectionGradingPeriods(section.sectionId),searchParams]);
 const selectablePeriods=periods.filter(p=>/^(Q[1-4]|S[12])$/.test(p.code));
 const selectedStudent=roster.find(s=>s.studentId===params.studentId)??roster[0];
 const selectedPeriod=selectablePeriods.find(p=>p.code===params.period)??selectablePeriods[0];
 const selectedSemesterCode=selectedPeriod&&isSemesterCode(selectedPeriod.code)?selectedPeriod.code:null;
 const fromSemester=isSemesterCode(params.fromSemester??"")?params.fromSemester as "S1"|"S2":null;
 const quarterCalculation=selectedStudent&&selectedPeriod&&!selectedSemesterCode?await getStudentGradeCalculation(section.sectionId,selectedStudent.studentId,selectedPeriod.code):null;
 const semesterCalculation=selectedStudent&&selectedSemesterCode?await getStudentSemesterCalculation(section.sectionId,selectedStudent.studentId,selectedSemesterCode):null;
 return <main className="app-shell grade-audit-shell"><header className="topbar"><div><p className="eyebrow">Teacher Gradebook</p><h1>Grade calculation audit</h1><p className="subtle">{section.courseName} • {section.sectionName} • deterministic engine output</p></div><div className="grade-audit-header-actions">{selectedStudent&&quarterCalculation&&fromSemester?<Link className="secondary-link" href={`?studentId=${selectedStudent.studentId}&period=${fromSemester}`}>← Back to {fromSemester} audit</Link>:null}<Link className="secondary-link" href="/gradebook">Back to Gradebook</Link><Link className="secondary-link" href="/">Dashboard</Link></div></header>
 <section className="content-wrap grade-audit-content"><article className="panel grade-audit-controls"><div className="panel-header"><div><p className="eyebrow">Audit controls</p><h3>Choose a student and grading period</h3></div></div><form method="get" className="grade-audit-form"><label><span>Student</span><select name="studentId" defaultValue={selectedStudent?.studentId} aria-label="Select student">{roster.map(s=><option key={s.studentId} value={s.studentId}>{s.displayName}{s.active?"":" (Inactive)"}</option>)}</select></label><label><span>Grading period</span><select name="period" defaultValue={selectedPeriod?.code} aria-label="Select grading period">{selectablePeriods.map(p=><option key={p.id} value={p.code}>{p.code} — {p.name}</option>)}</select></label><button className="primary-button grade-audit-submit" type="submit">View Calculation</button></form></article>
 {selectedStudent&&semesterCalculation?<SemesterAudit studentName={selectedStudent.displayName} semester={semesterCalculation}/>:selectedStudent&&quarterCalculation?<QuarterAudit studentName={selectedStudent.displayName} calculation={quarterCalculation} fromSemester={fromSemester}/>:<article className="panel full-width"><p className="subtle">No calculation data is available for this selection.</p></article>}
 </section></main>;
}

function SemesterAudit({studentName,semester}:{studentName:string;semester:Awaited<ReturnType<typeof getStudentSemesterCalculation>>}){
 return <><section className="metric-grid grade-audit-metrics" aria-label="Semester grade summary"><article className="metric-card"><span className="metric-label">Student</span><strong>{studentName}</strong></article><article className="metric-card"><span className="metric-label">Current {semester.semesterCode}</span><strong>{formatPercent(semester.result.overallPercent)}</strong></article>{semester.result.components.map(c=><article className="metric-card" key={c.code}><span className="metric-label">{c.label}</span><strong>{formatPercent(c.percent)}</strong><span className="subtle">Weight {(c.weight*100).toFixed(0)}%</span></article>)}</section>
 <article className="panel full-width"><div className="panel-header"><div><p className="eyebrow">Semester arithmetic</p><h3>{semester.semesterName}: weighted component calculation</h3></div></div><div className="integrity-stack">{semester.result.components.map(c=><div className="integrity-item" key={c.code}><span>{c.label}: {formatPercent(c.percent)} × {(c.weight*100).toFixed(0)}%</span><strong>{c.percent===null?"Excluded":c.weightedContribution.toFixed(2)}</strong></div>)}<div className="integrity-item success"><span>Weighted total ÷ active weight ({(semester.result.activeWeight*100).toFixed(0)}%)</span><strong>{formatPercent(semester.result.overallPercent)}</strong></div></div><p className="subtle">Components without data are excluded and the available weights are renormalized. Period composition will move to database configuration in the grading-period phase.</p></article>
 {semester.quarterCalculations.map(q=><article className="panel full-width" key={q.gradingPeriod.code}><div className="panel-header"><div><p className="eyebrow">Period component</p><h3>{q.gradingPeriod.code} — {formatPercent(q.result.overallPercent)}</h3></div><Link className="text-button" href={`?studentId=${q.studentId}&period=${q.gradingPeriod.code}&fromSemester=${semester.semesterCode}`}>Open period audit →</Link></div></article>)}
 {semester.examCalculation?<article className="panel full-width"><div className="panel-header"><div><p className="eyebrow">Exam component</p><h3>Semester Exam — {formatPercent(semester.examCalculation.result.overallPercent)}</h3></div></div><div className="assignment-table" role="table" aria-label="Semester exam audit">{semester.examCalculation.result.audit.map(line=><div className="assignment-row" role="row" key={line.assignmentId}><strong>{line.assignmentTitle??"Semester Exam"}</strong><span>{formatPercent(line.percent)}</span><span>{line.status}</span></div>)}</div></article>:null}</>;
}

function QuarterAudit({studentName,calculation,fromSemester}:{studentName:string;calculation:NonNullable<Awaited<ReturnType<typeof getStudentGradeCalculation>>>;fromSemester:"S1"|"S2"|null}){
 const categoryCodes=Object.keys(calculation.rules.categoryWeights);
 return <>{fromSemester?<div className="grade-audit-drillback"><span><strong>{calculation.gradingPeriod.code}</strong> within {fromSemester}</span><Link className="secondary-link" href={`?studentId=${calculation.studentId}&period=${fromSemester}`}>← Back to {fromSemester} audit</Link></div>:null}<section className="metric-grid grade-audit-metrics" aria-label="Student grade summary"><article className="metric-card"><span className="metric-label">Student</span><strong>{studentName}</strong></article><article className="metric-card"><span className="metric-label">Current {calculation.gradingPeriod.code}</span><strong>{formatPercent(calculation.result.overallPercent)}</strong></article>{categoryCodes.map(category=>{const result=calculation.result.categories[category];const method=calculation.rules.calculationMethods[category]??"equal_assignment_percentage";return <article className="metric-card" key={category}><span className="metric-label">{categoryLabel(category,calculation.rules)}</span><strong>{formatPercent(result?.averagePercent??null)}</strong><span className="subtle">Weight {(calculation.rules.categoryWeights[category]*100).toFixed(0)}% • {methodLabel(method)}</span></article>})}</section>
 <article className="panel full-width"><div className="panel-header"><div><p className="eyebrow">Category arithmetic</p><h3>How each configured category is calculated</h3></div></div><div className="integrity-stack">{categoryCodes.map(category=>{const r=calculation.result.categories[category];const label=categoryLabel(category,calculation.rules);const method=calculation.rules.calculationMethods[category]??"equal_assignment_percentage";if(!r)return <div className="integrity-item" key={category}><span>{label} — {methodLabel(method)} — no current grade data</span><strong>Excluded</strong></div>;const arithmetic=method==="total_points"?`${r.pointsEarned.toFixed(2)} / ${r.pointsPossible.toFixed(2)} = ${r.averagePercent.toFixed(2)}%`:`${r.assignmentCount} equally weighted assignment percentage${r.assignmentCount===1?"":"s"} = ${r.averagePercent.toFixed(2)}%`;return <div className="integrity-item" key={category}><span><strong>{label}</strong> · {methodLabel(method)} · {arithmetic} · weight {(r.configuredWeight*100).toFixed(0)}%</span><strong>{r.weightedContribution.toFixed(2)}</strong></div>})}<div className="integrity-item success"><span>Weighted total ÷ active weight ({(calculation.result.activeWeight*100).toFixed(0)}%)</span><strong>{formatPercent(calculation.result.overallPercent)}</strong></div></div><p className="subtle">Only categories with current counted or Missing grade data contribute to the active weight. Empty categories are excluded and the remaining category weights are renormalized.</p></article>
 <article className="panel full-width"><div className="panel-header"><div><p className="eyebrow">Assignment audit</p><h3>Exactly what counts</h3></div></div><div className="assignment-table" role="table" aria-label="Grade calculation audit"><div className="assignment-row table-head" role="row"><span>Assignment</span><span>Category</span><span>Counted score</span><span>Decision</span><span>Attempts</span></div>{calculation.result.audit.map(line=>{const countedPoints=line.countedPossible===null?"—":`${(line.countedEarned??0).toFixed(2)}/${line.countedPossible.toFixed(2)}`;return <div className="assignment-row" role="row" key={line.assignmentId}><span><strong>{line.assignmentTitle??line.assignmentId}</strong><br/><small>{line.assignmentDate??""}</small></span><span>{categoryLabel(line.category,calculation.rules)}</span><span>{countedPoints}<br/><small>{formatPercent(line.percent)}</small></span><span className={line.status==="counted"?"status success-pill":line.status==="missing"||line.status==="dropped"?"status warning-pill":"status"}>{line.status}{line.countedAttemptNumber?` · Attempt ${line.countedAttemptNumber}`:""}</span><span>{line.attempts.length===0?"—":line.attempts.map(a=>`${a.attemptNumber}: ${a.earned}/${a.possible} (${a.percent.toFixed(2)}%)${a.counted?" ✓":""}`).join(" · ")}</span></div>})}</div></article></>;
}
