import Link from "next/link";
import { redirect } from "next/navigation";
import { getSectionRoster } from "@/lib/data/roster";
import { getSectionGradingPeriods, getStudentGradeCalculation, getStudentSemesterCalculation } from "@/lib/data/grade-calculation";
import { getTeacherSections } from "@/lib/data/teacher-context";
import { createClient } from "@/lib/supabase/server";

function formatPercent(value:number|null){return value===null?"—":`${value.toFixed(2)}%`;}
function categoryLabel(category:string){return category==="participation"?"Participation":category==="quiz"?"Quizzes":category==="test"?"Tests":category;}
type GradebookPageProps={searchParams:Promise<{studentId?:string;period?:string}>};

export default async function GradebookPage({searchParams}:GradebookPageProps){
 const supabase=await createClient(); const {data:claimsData,error:claimsError}=await supabase.auth.getClaims(); const userId=claimsData?.claims?.sub;
 if(claimsError||typeof userId!=="string")redirect("/login");
 const sections=await getTeacherSections(); const section=sections[0]; if(!section)return <main className="content-wrap"><article className="panel"><h1>No teacher section is available.</h1></article></main>;
 const [roster,periods,params]=await Promise.all([getSectionRoster(section.sectionId,"all"),getSectionGradingPeriods(section.sectionId),searchParams]);
 const selectablePeriods=periods.filter(p=>/^(Q[1-4]|S[12])$/.test(p.code));
 const selectedStudent=roster.find(s=>s.studentId===params.studentId)??roster[0];
 const selectedPeriod=selectablePeriods.find(p=>p.code===params.period)??selectablePeriods[0];
 const isSemester=selectedPeriod?.code==="S1"||selectedPeriod?.code==="S2";
 const quarterCalculation=selectedStudent&&selectedPeriod&&!isSemester?await getStudentGradeCalculation(section.sectionId,selectedStudent.studentId,selectedPeriod.code):null;
 const semesterCalculation=selectedStudent&&selectedPeriod&&isSemester?await getStudentSemesterCalculation(section.sectionId,selectedStudent.studentId,selectedPeriod.code):null;
 return <main className="app-shell"><header className="topbar"><div><p className="eyebrow">Teacher Gradebook</p><h1>Grade calculation audit</h1><p className="subtle">{section.courseName} • {section.sectionName} • deterministic engine output</p></div><div className="toolbar-group"><Link className="secondary-button" href="/">Back to dashboard</Link></div></header>
 <section className="content-wrap"><article className="panel full-width"><div className="panel-header"><div><p className="eyebrow">Audit controls</p><h3>Choose a student and grading period</h3></div></div><form method="get" className="toolbar-group"><select name="studentId" defaultValue={selectedStudent?.studentId} aria-label="Select student">{roster.map(s=><option key={s.studentId} value={s.studentId}>{s.displayName}{s.active?"":" (Inactive)"}</option>)}</select><select name="period" defaultValue={selectedPeriod?.code} aria-label="Select grading period">{selectablePeriods.map(p=><option key={p.id} value={p.code}>{p.code} — {p.name}</option>)}</select><button className="primary-button" type="submit">View Calculation</button></form></article>
 {selectedStudent&&semesterCalculation?<SemesterAudit studentName={selectedStudent.displayName} semester={semesterCalculation}/>:selectedStudent&&quarterCalculation?<QuarterAudit studentName={selectedStudent.displayName} calculation={quarterCalculation}/>:<article className="panel full-width"><p className="subtle">No calculation data is available for this selection.</p></article>}
 </section></main>;
}

function SemesterAudit({studentName,semester}:{studentName:string;semester:Awaited<ReturnType<typeof getStudentSemesterCalculation>>}){
 return <><section className="metric-grid" aria-label="Semester grade summary"><article className="metric-card"><span className="metric-label">Student</span><strong>{studentName}</strong></article><article className="metric-card"><span className="metric-label">Current {semester.semesterCode}</span><strong>{formatPercent(semester.result.overallPercent)}</strong></article>{semester.result.components.map(c=><article className="metric-card" key={c.code}><span className="metric-label">{c.label}</span><strong>{formatPercent(c.percent)}</strong><span className="subtle">Weight {(c.weight*100).toFixed(0)}%</span></article>)}</section>
 <article className="panel full-width"><div className="panel-header"><div><p className="eyebrow">Semester arithmetic</p><h3>{semester.semesterName}: dynamic 40 / 40 / 20 calculation</h3></div></div><div className="integrity-stack">{semester.result.components.map(c=><div className="integrity-item" key={c.code}><span>{c.label}: {formatPercent(c.percent)} × {(c.weight*100).toFixed(0)}%</span><strong>{c.percent===null?"Excluded":c.weightedContribution.toFixed(2)}</strong></div>)}<div className="integrity-item success"><span>Weighted total ÷ active weight ({(semester.result.activeWeight*100).toFixed(0)}%)</span><strong>{formatPercent(semester.result.overallPercent)}</strong></div></div><p className="subtle">Components without data are excluded and the available weights are renormalized. This keeps the current semester grade meaningful before every component exists.</p></article>
 {semester.quarterCalculations.map(q=><article className="panel full-width" key={q.gradingPeriod.code}><div className="panel-header"><div><p className="eyebrow">Quarter component</p><h3>{q.gradingPeriod.code} — {formatPercent(q.result.overallPercent)}</h3></div><Link className="text-button" href={`?studentId=${studentName ? q.studentId : q.studentId}&period=${q.gradingPeriod.code}`}>Open quarter audit</Link></div></article>)}
 {semester.examCalculation?<article className="panel full-width"><div className="panel-header"><div><p className="eyebrow">Exam component</p><h3>Semester Exam — {formatPercent(semester.examCalculation.result.overallPercent)}</h3></div></div><div className="assignment-table" role="table" aria-label="Semester exam audit">{semester.examCalculation.result.audit.map(line=><div className="assignment-row" role="row" key={line.assignmentId}><strong>{line.assignmentTitle??"Semester Exam"}</strong><span>{formatPercent(line.percent)}</span><span>{line.status}</span></div>)}</div></article>:null}</>;
}

function QuarterAudit({studentName,calculation}:{studentName:string;calculation:NonNullable<Awaited<ReturnType<typeof getStudentGradeCalculation>>>}){
 return <><section className="metric-grid" aria-label="Student grade summary"><article className="metric-card"><span className="metric-label">Student</span><strong>{studentName}</strong></article><article className="metric-card"><span className="metric-label">Current {calculation.gradingPeriod.code}</span><strong>{formatPercent(calculation.result.overallPercent)}</strong></article>{(["participation","quiz","test"] as const).map(category=><article className="metric-card" key={category}><span className="metric-label">{categoryLabel(category)}</span><strong>{formatPercent(calculation.result.categoryPercents[category]??null)}</strong><span className="subtle">Weight {(calculation.rules.categoryWeights[category]*100).toFixed(0)}%</span></article>)}</section>
 <article className="panel full-width"><div className="panel-header"><div><p className="eyebrow">Final arithmetic</p><h3>Active category weighting</h3></div></div><div className="integrity-stack">{(["participation","quiz","test"] as const).map(category=>{const r=calculation.result.categories[category];return !r?<div className="integrity-item" key={category}><span>{categoryLabel(category)} — no current data</span><strong>Excluded</strong></div>:<div className="integrity-item" key={category}><span>{categoryLabel(category)}: {r.averagePercent.toFixed(2)}% × {(r.configuredWeight*100).toFixed(0)}%</span><strong>{r.weightedContribution.toFixed(2)}</strong></div>})}<div className="integrity-item success"><span>Weighted total ÷ active weight ({(calculation.result.activeWeight*100).toFixed(0)}%)</span><strong>{formatPercent(calculation.result.overallPercent)}</strong></div></div></article>
 <article className="panel full-width"><div className="panel-header"><div><p className="eyebrow">Assignment audit</p><h3>Exactly what counts</h3></div></div><div className="assignment-table" role="table" aria-label="Grade calculation audit"><div className="assignment-row table-head" role="row"><span>Assignment</span><span>Category</span><span>Counted score</span><span>Decision</span><span>Attempts</span></div>{calculation.result.audit.map(line=><div className="assignment-row" role="row" key={line.assignmentId}><span><strong>{line.assignmentTitle??line.assignmentId}</strong><br/><small>{line.assignmentDate??""}</small></span><span>{categoryLabel(line.category)}</span><span>{formatPercent(line.percent)}</span><span className={line.status==="counted"?"status success-pill":line.status==="missing"||line.status==="dropped"?"status warning-pill":"status"}>{line.status}{line.countedAttemptNumber?` · Attempt ${line.countedAttemptNumber}`:""}</span><span>{line.attempts.length===0?"—":line.attempts.map(a=>`${a.attemptNumber}: ${a.earned}/${a.possible} (${a.percent.toFixed(2)}%)${a.counted?" ✓":""}`).join(" · ")}</span></div>)}</div></article></>;
}
